name: mechdriver-env

channels:
    - auto-mech
    - psi4
    - rdkit
    - openbabel
    - conda-forge

dependencies:
    - python=3.7
    - pybind11
    - cmake
    - gcc_linux-64  # [linux]
    - gxx_linux-64  # [linux]
    - gfortran_linux-64  # [linux]
    - numpy
    - scipy
    - pandas
    - pyyaml
    - mako
    - pytest
    - pytest-cov
    - future
    - flake8
    - pylint
    - psi4::psi4
    - rdkit::rdkit
    - openbabel::openbabel
    - conda-forge::qcelemental 
    - conda-forge::nglview
    - conda-forge::pypdf2
    - conda-forge::python-igraph
    - cantera::cantera
    - auto-mech::autofile
    - auto-mech::autoio
    - auto-mech::autoparse
    - auto-mech::elstruct
    - auto-mech::automol
    - auto-mech::ratefit
    - auto-mech::mechanalyzer
    - auto-mech::mess
    - auto-mech::mpack
    - auto-mech::pac99
    - auto-mech::projrot
    - auto-mech::slatec
    - auto-mech::thermp
    - auto-mech::x2z
