name: moldr-env

channels:
    - pacchem
    - psi4
    - rdkit
    - openbabel
    - conda-forge

dependencies:
    - python=3.7
    - numpy
    - pyyaml
    - pytest
    - pytest-cov
    - future
    - flake8
    - pylint
    - rdkit::rdkit
    - openbabel::openbabel
    - psi4::psi4
    - pacchem::autoparse
    - pacchem::autochem
    - pacchem::elstruct
