name: mechdriver-env

channels:
    - auto-mech
    - psi4
    - rdkit
    - openbabel
    - conda-forge

dependencies:
    - gfortran_linux-64  # [linux]
    - python=3.7
    - numpy=1.15.4
    - scipy=1.5.0
    - gcc_linux-64  # [linux]
    - gxx_linux-64  # [linux]
    - pyyaml
    - cmake
    - mako
    - networkx
    - matplotlib
    - pytest
    - pytest-cov
    - future
    - flake8
    - pylint
    - pandas
    - psi4::psi4
    - rdkit::rdkit
    - openbabel::openbabel
    - conda-forge::qcelemental
    - auto-mech::autochem
    - auto-mech::autoio-base
    - auto-mech::x2z
    - auto-mech::mess
    - auto-mech::onedmin
    - auto-mech::projrot
    - auto-mech::pac99
    - auto-mech::thermp
    - auto-mech::autoio-interfaces
    - auto-mech::autofile
    - auto-mech::mechanalyzer
