name: moldriver-env

channels:
    - kevinmooreiii
    - auto-mech
    - psi4
    - rdkit
    - openbabel
    - conda-forge

dependencies:
    - python=3.7
    - numpy
    - scipy
    - pyyaml
    - mako
    - matplotlib
    - pytest
    - pytest-cov
    - future
    - flake8
    - pylint
    - rdkit::rdkit
    - openbabel::openbabel
    - conda-forge::qcelemental
    - psi4::psi4
    # AutoMech
    - kevinmooreiii::autofile
    - kevinmooreiii::automol
    - kevinmooreiii::autoparse
    - kevinmooreiii::elstruct
    - kevinmooreiii::interfaces
    - kevinmooreiii::rateFit
    - auto-mech::mess
    - auto-mech::pac99
    - auto-mech::projrot
    - auto-mech::thermp
    - auto-mech::x2z
    - auto-mech::slatec
    - auto-mech::mpack
