name: moldr-env

channels:
    - auto-mech
    - psi4
    - rdkit
    - openbabel
    - conda-forge

dependencies:
    - python=3.7
    - numpy
    - pyyaml
    - pytest
    - pytest-cov
    - future
    - flake8
    - pylint
    - rdkit::rdkit
    - openbabel::openbabel
    - psi4::psi4
    # Python
    - auto-mech::autofile
    - auto-mech::automol
    - auto-mech::autoparse
    - auto-mech::elstruct
    - auto-mech::interfaces
    - auto-mech::RateFit
    # Installable
    - auto-mech::MESS
    - auto-mech::SLATEC
    - auto-mech::MPACK
    - auto-mech::PAC99
    - auto-mech::ThermP
    - auto-mech::ProjRot  
    - auto-mech::x2z
