# cmd: conda build . -c auto-mech -c psi4 -c rdkit -c openbabel -c conda-forge
package:
    name: mechanalyzer
    version: "0.1.0"

source:
    path: .

requirements:
    host:
        - python
    build:
        - cmake
    run:
        - cmake
        - gfortran_linux-64
        - gcc_linux-64
        - python
        - numpy
        - scipy
        - pyyaml
        - mako
        - matplotlib
        - pytest
        - pytest-cov
        - future
        - flake8
        - pylint
        - rdkit::rdkit
        - openbabel::openbabel
        - conda-forge::qcelemental
        - psi4::psi4
        - auto-mech::autoio
        - auto-mech::automol
        - auto-mech::autoparse
        - auto-mech::elstruct
        - auto-mech::ratefit
        - auto-mech::mechanalyzer
        - auto-mech::mess
        - auto-mech::mpack
        - auto-mech::pac99
        - auto-mech::projrot
        - auto-mech::slatec
        - auto-mech::thermp
        - auto-mech::x2z
