# cmd: conda build . -c auto-mech -c psi4 -c rdkit -c openbabel -c cantera -c conda-forge
package:
    name: mechdriver
    version: "0.1.0"

source:
    path: .

requirements:
    host:
        - python=3.7
    build:
        - cmake
        - gfortran_linux-64
    run:
        - python=3.7
        - pybind11
        - cmake
        - gfortran_linux-64  # [linux]
        - numpy
        - scipy
        - pandas
        - pyyaml
        - mako
        - matplotlib
        - pytest
        - pytest-cov
        - future
        - flake8
        - pylint
        - psi4::psi4
        - rdkit::rdkit
        - openbabel::openbabel
        - conda-forge::qcelemental
        - conda-forge::nglview
        - conda-forge::pypdf2
        - conda-forge::python-igraph
        - cantera::cantera
        - auto-mech::autochem
        - auto-mech::autofile
        - auto-mech::autoio-base
        - auto-mech::autoio-interfaces
        - auto-mech::ratefit
        - auto-mech::mechanalyzer
        - auto-mech::mess
        - auto-mech::pac99
        - auto-mech::projrot
        - auto-mech::thermp
        - auto-mech::x2z
