package:
  name: mechdriver
  version: "2024.6.4"

about:
  license: MIT
  description: Automated workflow routines for calculating theoretical data for reaction mechanisms
  repository: https://github.com/Auto-Mech/mechdriver

source:
  path: .

build:
  noarch: python
  script: pip install . -v --no-deps

requirements:
  host:
    - pip
    - python >=3.10
    - poetry
    - wheel
  run:
    - python >=3.10
    - pip
    - numpy
    - pylint
    - pytest
    - scipy
    - click
    - auto-mech::autochem
    - auto-mech::autoio
    - auto-mech::autofile
    - auto-mech::mechanalyzer
