version: 2
jobs:
    test-mechdriver:
        docker:
            - image: continuumio/miniconda3
        steps:
            - checkout  # checkout the code
            - run: 
                name: Create conda environment
                command: |
                    apt-get update --yes
                    apt-get install --yes libxrender-dev build-essential
                    conda env create -f environment.yml
            - run:
                name: Build/install mechdriver
                command: |
                    source activate mechdriver-env
                    python setup.py install
            - run:
                name: Test mechdriver pep8
                command: |
                    source activate mechdriver-env
                    flake8 --exit-zero ../mechdriver
                    pylint --rcfile=../.pylintrc mechdriver
workflows:
    version: 2
    build-all:
        jobs:
            - test-mechdriver
