version: 2
jobs:
    test-mechdriver:
        docker:
            - image: continuumio/miniconda3
        working_directory: ~/mechdriver
        steps:
            - checkout  # checkout the code
            - run: 
                name: Create conda environment
                command: |
                    apt-get update --yes
                    apt-get install --yes libxrender-dev build-essential
                    conda env create -f environment.yml
            - run:
                name: Build/install mechdriver
                command: |
                    source activate mechdriver-env
                    python setup.py install
            - run:
                name: Test mechdriver
                no_output_timeout: 60m
                command: |
                    export PYTHONUNBUFFERED=1
                    source activate mechdriver-env
                    pytest -v --disable-pytest-warnings --cov=mechlib --cov=mechroutines --cov=drivers --cov-report=html
                    coverage report
            - run:
                name: Assess PEP8
                command: |
                    source activate mechdriver-env
                    flake8 --exit-zero mechlib
                    pylint --rcfile=.pylintrc mechlib
                    flake8 --exit-zero mechroutines
                    pylint --rcfile=.pylintrc mechroutines
                    flake8 --exit-zero drivers
                    pylint --rcfile=.pylintrc drivers
            - store_artifacts:
                    path: htmlcov
workflows:
    version: 2
    build-all:
        jobs:
            - test-mechdriver
