jobs:
    build-debian:
        docker:
            - image: continuumio/miniconda3
        steps:
            - checkout  # checkout the code
            - run: 
                name: Create conda environment
                command: |
                    apt-get update --yes
                    apt-get install --yes libxrender-dev  # needed for rdkit
                    conda env create -f environment.yml
            - run:
                name: Test autofile
                command: |
                    source activate moldr-env
                    python setup.py install
                    cd autofile
                    pytest -v --cov=autofile --pyargs autofile
                    flake8 --exit-zero autofile
                    pylint --rcfile=../.pylintrc autofile
            - run:
                name: Test moldr
                command: |
                    source activate moldr-env
                    cd scripts 
                    python estoktp.py
workflows:
    version: 2
    build-all:
        jobs:
            - build-debian
