version: 2
jobs:
    build-debian:
        docker:
            - image: continuumio/miniconda3
        steps:
            - checkout  # checkout the code
            - run: 
                name: Create conda environment
                command: |
                    apt-get update --yes
                    apt-get install --yes libxrender-dev build-essential
                    conda env create -f environment.yml
            - run:
                name: Build/install moldriver
                command: |
                    source activate moldriver-env
                    python setup.py install
            # - run:
            #    name: Test moldriver
            #    command: |
            #        source activate moldriver-env
            #        pytest -v --cov=moldriver --pyargs moldriver
            - run:
                name: Pylint bin
                command: |
                    source activate moldriver-env
                    flake8 --exit-zero bin
                    pylint --rcfile=../.pylintrc bin
            - run:
                name: Pylint drivers
                command: |
                    source activate moldriver-env
                    flake8 --exit-zero drivers
                    pylint --rcfile=../.pylintrc drivers
            - run:
                name: Pylint routines
                command: |
                    source activate moldriver-env
                    flake8 --exit-zero routines
                    pylint --rcfile=../.pylintrc routines
            - run:
                name: Pylint lib
                command: |
                    source activate moldriver-env
                    flake8 --exit-zero lib
                    pylint --rcfile=../.pylintrc lib
workflows:
    version: 2
    build-all:
        jobs:
            - build-debian
