[project]
name = "mechanalyzer"
version = "2025.7.28"
description = "Tools construction, manipulation, visualization of chemical mechanisms"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "click>=8.2.1",
    "mako",
    "matplotlib",
    "networkx",
    "numpy",
    "pandas",
    "python-igraph",
    "pyyaml",
    "scipy",
]

[project.scripts]
mechanalyzer = "mechanalyzer.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
include = ["mechanalyzer", "ratefit", "thermfit"]

[tool.hatch.build.targets.wheel]
include = ["mechanalyzer", "ratefit", "thermfit"]

[dependency-groups]
dev = [
    "pytest",
]
