name: check-signature 

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check-signature:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        # Signature check needs git history of previous commits
        with:
          fetch-depth: 10

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.9.1
        with:
          environments: test
          frozen: true

      - name: Check signature
        run: |
          pixi run --frozen -e test pytest -v tests/ -k "signature"
